### ISSUE TITLE
Experimental nightly, ranks and placeholders, languages, doesn't works.

### ISSUE THREAD

**Issue by GABRYCA** [PrisonTeam/Prison#101]
Ranks, language, spigot, experimental nightly.

I installed the experimental version, there're 2 bugs.
First: Ranks doesn't works, for example /ranks doesn't exist and placeholder doesn't work.
Second: Language don't change.

To see the problem, try to do /ranks, nothing happen, only an error "that command doesn't exist, try /help for a list of commands

I think the problem it's in the place of "ranks".
For language i don't know, i hope my it_IT.properties wasn't broken.

**Comment by DylanFPS** [comment]
Did this get fixed in the end?
