### ISSUE TITLE
I need a little help here!

### ISSUE THREAD

**Issue by lMagicP** [PrisonTeam/Prison#107]
i have an error in the console and i don't what causes it 

**Console LOG:**

ServersisPRISONConsole
Server Console

24.06 17:12:33 [Multicraft] Skipped 32 lines due to rate limit (30/s)
24.06 17:12:33 [Server] ERROR Could not pass event PlayerInteractEvent to Prison v3.1.1
24.06 17:12:33 [Server] INFO org.bukkit.event.EventException
24.06 17:12:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.BlockRedstoneOre.a(BlockRedstoneOre.java:37) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:688) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:408) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
24.06 17:12:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
24.06 17:12:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
24.06 17:12:33 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant tech.mcprison.prison.internal.events.player.PlayerInteractEvent.Action.PHYSICAL
24.06 17:12:33 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_171]
24.06 17:12:33 [Server] INFO at tech.mcprison.prison.internal.events.player.PlayerInteractEvent$Action.valueOf(PlayerInteractEvent.java:72) ~[?:?]
24.06 17:12:33 [Server] INFO at tech.mcprison.prison.spigot.SpigotListener.onPlayerInteract(SpigotListener.java:115) ~[?:?]
24.06 17:12:33 [Server] INFO at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[?:?]
24.06 17:12:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
24.06 17:12:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
24.06 17:12:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]

**Comment by lMagicP** [comment]
PD: is my first time writing a issue

**Comment by DylanFPS** [comment]
Ah yeah this is a known issue - we have a fix on the nightly server, you can grab it [here](https://ci.appveyor.com/project/faizaand/prison/build/artifacts)
