### ISSUE TITLE
Rank-Mines Integration

### ISSUE THREAD

**Issue by CottonBawl** [PrisonTeam/Prison#108]
Is there a way to restrict mines for certain ranks. Like, Rank A can visit Mine A. and Rank B can visit Mines A and B. But Rank A cannot visit Mine B

**Comment by DylanFPS** [comment]
This is done using permissions - read the [Rank Guidebook](https://confluence.onultz.com/prison/ranks-guidebook)

**Comment by faizaand** [comment]
The fact that so many people have the same question means that it's the _software_ that's the problem. I propose a more developed system of ranks-mines integration in which:
* Mines can be added to each rank.
* Ranks inherit mines from previous ones down the ladder.
* Inbuilt mines protection: only ranks that are added to a mine can mine in them.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.

**Comment by GABRYCA** [comment]
mines.tp permission's already a thing and should works if you add it to the player on rankup
