### ISSUE TITLE
Andesite is turning into stone in mines.

### ISSUE THREAD

**Issue by Fez-Masta77** [PrisonTeam/Prison#109]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Mines
### Describe the issue you are experiencing.
Whenever I set up my mine with andesite (1:5) and smooth stone (1:0) the andesite always changes to smooth stone after I restart my server. I want to have a mine with 50% smooth stone, 35% cobblestone, and 15% andesite. 
TL;DR: The mine isn't remembering data values after I restart my server.
### Describe the steps to reproduce the problem.
Spigot: 1.12.2-R0.1-SNAPSHOT
Prison: 3.1.1
1) create a mine /mines create test
2) populate the mine with blocks /mines block add test 1:0 50 /mines block add test 4 35 /mines block add test 1:5 15
3) reset the mine /mines reset test
4) restart the server
5) reset the mine again /mines reset test
### Anything else we need to know?
my spigot is outdated because I don't know how to update it.

**Comment by Fez-Masta77** [comment]
also happens if you use names instead of ids (stone, cobblestone, andesite)

**Comment by faizaand** [comment]
@Fez-Masta77 I see you closed the issue, did you solve it?
