### ISSUE TITLE
Demote command

### ISSUE THREAD

**Issue by Perksey** [PrisonTeam/Prison#110]
Alright. We somehow seem to have completely overlooked something basic in Prison 3:
```
/ranks demote [player]
```
This command will move the player down the ladder, and should be a moderator only command.

**Comment by rbluer** [comment]
Closing this since rank commands have been added to the upcoming v3.2.1 release.

/ranks promote [player] [ladder]
/ranks demote [player] [ladder]
/ranks set rank [player] [rank] [ladder]
