### ISSUE TITLE
Troubleshooting and support tools (Support Zips)

### ISSUE THREAD

**Issue by Perksey** [PrisonTeam/Prison#111]
The support zip feature would allow for easy troubleshooting for the Support team. This feature would make a zip including the data and configs, to the extent configurable by the user.

This would be a lot better for us as users often fail to give the detail we require in their support requests.

### How it would work
Something is wrong with the plugin and they are about to make a support request, so they:

- Type `/prison zip`
- Prison then collects all of the configuration and data, and puts it in a zip file
- Prison then stores this zip file in the root of the Prison data dir
- The user can then DM this file to us on Discord and make a support request

### Why this should be done in the core module
This would allow the system to work on each platform without requiring us to duplicate our code per platform. The support zip will include basic information about the server, such as the platform and versions. It will also include all of the user's configuration, unless the user has specified a certain zip to be created i.e. `/prison zip mines`, `/prison zip ranks`, `/prison zip mines ranks`

**Comment by DylanFPS** [comment]
@faizaand thoughts? I think it will make our life easier in regards to support.

**Comment by faizaand** [comment]
Seems like a good idea, do you want to take care of this?

**Comment by DylanFPS** [comment]
Yep, i'll take it.

**Comment by DylanFPS** [comment]
UPDATE: removed the ability to select the contents of the zip to reduce iterations.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
