### ISSUE TITLE
Breaking Blocks

### ISSUE THREAD

**Issue by Fralacop** [PrisonTeam/Prison#113]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
Permissions to break blocks in a mine.

### Describe the steps to reproduce the problem.
deop myself

### Anything else we need to know?

Im using EssentialsX

**Comment by DylanFPS** [comment]
Thanks for using Prison! Whether a player can or cannot break blocks in a mine is not controlled by Prison, it'll be another plugin you're using.
