### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by Fralacop** [PrisonTeam/Prison#114]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.
I cannot seem to find the prefix command for ranks. I do /ranks create b 100 default &7[&3B&7]

### Anything else we need to know?

Im using EssentialsX

**Comment by DylanFPS** [comment]
Thanks for using Prison! You've got that command spot on, however you need to perform more steps before you can use the prefix. To get the rank prefixes showing up in chat, you'll need a chat plugin, such as EssentialsX-Chat. Simply add the tag {PRISON_RANK} to your chat format. If you don't know how to do this, read up on the EssentialsX documentation.

## Support Offerings
This GitHub issue page is strictly a bug tracking page. If you want to get support, you can try our [Discord support channel](https://discord.gg/396ed5F). Support is provided on a best-effort basis and is not guaranteed.
