### ISSUE TITLE
Rankup Permissions

### ISSUE THREAD

**Issue by Fralacop** [PrisonTeam/Prison#115]
### Which module are you submitting this issue for?
Ranks

### Question 
How do i give permissions when people rank up?

### Anything else we need to know?
Im using PermissionsEx

**Comment by GABRYCA** [comment]
you can visit our "[Ranks Guidebook](https://confluence.onultz.com/prison/docs/latest/en/ranks-guidebook)" and add when a player rankup a permission with this command: `/ranks command add [Rank] pex user {player} add [permission] `
You should remember this syntax: `/rank command add [Rank] [Command]`

{Player] it's a tag, when a player execute that command, automatically {player} became the name of the executior (In simple terms)

**Comment by SevenSlayy** [comment]
Please read over this: https://confluence.onultz.com/display/PRIS/Ranks+Guidebook
To add a group, use /ranks command add YourRank pex user {player} group add YourGroup

**Comment by DylanFPS** [comment]
Thanks for using Prison! Please stop opening support issues on our **bug** tracker. That command is valid, I don't see your point?

**Comment by Fralacop** [comment]
okay but one question where do i post support issues?

**Comment by DylanFPS** [comment]
In the aforementioned [discord support channel](https://discord.gg/f7kgbyN).
