### ISSUE TITLE
Mines reset message accessibility improvements.

### ISSUE THREAD

**Issue by Perksey** [PrisonTeam/Prison#120]
Changing mine reset messages are FAQ-able, and they shouldn't be. The user should be able to look through the configs and figure out what variables are the mine reset messages. So I propose 2 solutions:

### 1) We move the messages into config.json
Like they used to be before 3.0.0 - users will find the messages easier, but will need some mechanism to move their changed values in the lang file to the config file

### 2) We auto-create a mines lang file
This is more compatible than option 1. If there isn't a lang file, we create it prefilled with the message variables and nothing else. If there is a lang file but it doesn't contain the message variables, we add them in to make sure that the user will definately notice those flippin variables!

**Comment by DylanFPS** [comment]
cc: @faizaand

**Comment by faizaand** [comment]
Problem with this is that reset messages are a translatable thing.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
