### ISSUE TITLE
Can't have decimal chance percentages of blocks in a mine

### ISSUE THREAD

**Issue by MrNirost** [PrisonTeam/Prison#124]
### Which module are you submitting this issue for?

Mines

### Describe the issue you are experiencing.
I can't have decimal percentages of blocks in a mine.
For example, I don't want to have too many diamonds in a mine but the mininum percentage is 1 which is too much.
### Describe the steps to reproduce the problem.
Tried to set diamond_ore in a mine to 0.05 chance.
### Anything else we need to know?
No

**Comment by rbluer** [comment]
I just added this feature on my fork: https://github.com/rbluer/Prison

Currently it is in a prerelease state, but I will be releasing the final version shortly.  I'm wanting to perform more testing and maybe add a few more features before finalizing the version.

**Comment by Perksey** [comment]
@rbluer Hey! Thanks for continuing Prison's legacy. Get in touch with me on Discord so we can talk about the future of Prison :P

**Comment by rbluer** [comment]
Release v3.2.0 has added this feature.  Please download the Prison plugin v3.2.0 when it is available.
