### ISSUE TITLE
Deleted mines come back after a restart

### ISSUE THREAD

**Issue by 0rbas** [PrisonTeam/Prison#125]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: Core, Mines, Ranks, Shops, Cells, Gangs, Spigot, Sponge, etc.
Mines

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.
When you do /mines delete "mine name" it deletes the mine but when the server restarts the mine comes back.
### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only 
needed if you are making a bug report.
Make a mine, delete it, restart the server.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by GABRYCA** [comment]
Hi, which server version are you using? Because on 1.12 i can't cause the same problem

**Comment by 0rbas** [comment]
1.8

**Comment by GABRYCA** [comment]
Oh sorry i forgot about this.
Anyway to me it happen on 1.8.8 and before, on 1.8.9 to 1.12.2 it doesn't

**Comment by rbluer** [comment]
This issue is related to the saving of the data. If the server fails to stop cleanly, such as with /stop (not sure about /restart), then it will never save the mine data and any changes since the start of the server will be lost: includes creating new mines, changing mines, or deleting mines.
I should have a fix for this within the next few days.

**Comment by rbluer** [comment]
Release v3.2.0 has addressed a number of issues that contributed to this issue.  Please download the Prison plugin v3.2.0 when it is available.
