### ISSUE TITLE
Prison Core

### ISSUE THREAD

**Issue by Nullfic** [PrisonTeam/Prison#126]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Core

### Describe the issue you are experiencing.
Unaware of how I'm able to change & edit the messages of the plugin, as in the config there is no message formatting.

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by svnxd** [comment]
I believe you can use the files in the lang file to change some messages, past that point, you can modify the source code from here.

**Comment by DylanFPS** [comment]
This is covered in our documentation https://faizaan.xyz/prison

**Comment by GABRYCA** [comment]
Except for the "info" word at the start of the message, it can't be changed

**Comment by DylanFPS** [comment]
@GABRYCA Fixed in #127

**Comment by Perksey** [comment]
Pretty much covered in #131
