### ISSUE TITLE
Some language messages cannot be edited in the configuration file

### ISSUE THREAD

**Issue by HuJunwei23333** [PrisonTeam/Prison#131]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: language

### Describe the issue you are experiencing.
I translated the language configuration file but some of the content could not be translated

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by Perksey** [comment]
Hi there! Unfortunately, we are no-longer developing Prison and, unless done so by a passionate community member, we will release no further updates.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
