### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Toomas633** [PrisonTeam/Prison#133]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Spigot, Mines

### Describe the issue you are experiencing.

When i try to add blocks to a mine it just says that an internall error has occured and when i try to see the mine's info after that it again shows an internal error. And after i restart my server, during booting essentials starts spitting out errors.

### Anything else we need to know?

I'm running latest 1.14.3 spigot with a couple of other plugins. Intel i7-8750H, 12Gb RAM

Plugins:
EssetnialsX, Dynmap, Jobs, LuckPerms, Vault, WorldBorder, ChestShop, ServerMonitor, SuperVanish, Ultimate Economy, Worldedit, Worldguard

Server log image:
![12 07 2019](https://user-images.githubusercontent.com/52831344/61140876-fb70b380-a4d4-11e9-896b-3d14e23151a3.PNG)

**Comment by Perksey** [comment]
It looks like Spigot removed a set of APIs we depended on. Unfortunately, there's no fix in sight due to the dissolution of the Prison Team, but I'll leave this open just in case someone from the community picks it up.

**Comment by GABRYCA** [comment]
I could but i have to learn more before do it.
I'm sorry

**Comment by rbluer** [comment]
Version 1.14.x has general failures due to changes in supported libraries.

I have ideas on how to address this but I'm unsure the extend of this issue; if this is an isolated situation or are there many other library changes?  

I will eventually get to this since I would like to get this functional on 1.14.x but unsure of the timing.  Perhaps a few weeks out?

**Comment by rbluer** [comment]
Release v3.2.0 works well in 1.14.4. Please download the Prison plugin v3.2.0 when it is available.
