### ISSUE TITLE
Error ?????

### ISSUE THREAD

**Issue by roseboii99999** [PrisonTeam/Prison#134]
[If](url
![prismnotworking](https://user-images.githubusercontent.com/54394239/63497749-4f2dcf80-c479-11e9-8c6a-d18be3358b8f.PNG)
) you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: Core, Mines, Ranks, Shops, Cells, Gangs, Spigot, Sponge, etc.

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by svnxd** [comment]
1.13 and above are not supported

**Comment by GABRYCA** [comment]
Yeah and that prism isn't helping at all

**Comment by Perksey** [comment]
This repository is for the **Prison** plugin, not the **Prism** plugin.
