### ISSUE TITLE
error when add block to mines

### ISSUE THREAD

**Issue by akiragunawan** [PrisonTeam/Prison#135]
I want to claim error for mine section.
it starts when I have created mine with no problem, but the problem is when I adding block into the mine using
/mines block add <minename> <block> <chance>
the error is listed below in the log file, I use essentialsx for the economy and pex as the permission for ranks
[latest.log](https://github.com/PrisonTeam/Prison/files/3534778/latest.log)

thanks for the help :D

**Comment by GABRYCA** [comment]
1.14 not supported, sorry

**Comment by akiragunawan** [comment]
its my fault then :(, im sorry
