### ISSUE TITLE
When mine resets no tp

### ISSUE THREAD

**Issue by MrGamezYT** [PrisonTeam/Prison#136]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Mines

### Describe the issue you are experiencing.
when you do /mine reset [mine] you dont get tped to the set spawnpoint for the mine

### Describe the steps to reproduce the problem.
i make the mine, with blocks and everything, i go a bit down in the mine and type /mine reset [mine]

### Anything else we need to know?

not really

**Comment by GABRYCA** [comment]
Please, can you say the minecraft server version?

**Comment by MrGamezYT** [comment]
it's multi version, but i play on 1.12.2
i think, not sure it is 1.9 till 1.14 not sure, ill check

**Comment by MrGamezYT** [comment]
1.8 till 1.14 is the server, but i played on forge 1.12.2 for shaders and optifine

**Comment by GABRYCA** [comment]
So the server it's spigot 1.8 with ViaVersion, so you can play with 1.14 too?
Or i'm wrong...

**Comment by MrGamezYT** [comment]
no i was wrong xD its 1.12.2 till 1.14, but it is from 1.12.2 spigot with viaversion yes

**Comment by GABRYCA** [comment]
So the version shouldn't be the issue...
Right now i'm sorry but i have no idea of what could be to make the TP not working... as maybe (but probably i'm wrong), the top of the mine have obstacles or an upper floor which maybe trigger the TP.
You could try to make a mine in an empty place, just to check if it works.
I mever

**Comment by MrGamezYT** [comment]
ok, ill look

**Comment by rbluer** [comment]
Release v3.2.0 has number of changes that will prevent this from happening.  Please download the Prison plugin v3.2.0 when it is available.

Note: Players that set homes in the mine or logoff and back in after the mines reset are out of luck.  Future releases *may* address these edge cases.
