### ISSUE TITLE
Server crash (Stopped responding)

### ISSUE THREAD

**Issue by ItzRonaldLG** [PrisonTeam/Prison#138]
#112 # Which module are you submitting this issue for?

Spigot, Crash

### Describe the issue you are experiencing.
I made all the mines from the alphabet from A-Z.
(I assume) When the mines reset automatically the server will crash...
Before saying ''Try to see what plugin conflicts'', Yes i have tested multiple days different things and i cant figure it out.
When i delete the mines folder and let it create a new one and then make 1 mine to test, nothing happens, no crash...
When i put my mines folder with all the mines A-Z in, i will crash again.
Log: https://pastebin.com/TdzbD1yJ
Mines: https://mega.nz/#F!MllnAArR!679nlLHIBPYbiPyzE5FKIg

### Describe the steps to reproduce the problem.
Start server with many mines configured to reset.

### Anything else we need to know?

Is there something wrong with the mines? i dont see any problem. I'm verry sure there is no conflicting plugin.

**Comment by GABRYCA** [comment]
Maybe you did a reload and something got corrupted in the plugin/folder, this is an important error:
`[16:04:19] [Spigot Watchdog Thread/ERROR]:      tech.mcprison.prison.mines.managers.MineManager$$Lambda$235/598384078.accept(Unknown Source)`

I'll try later to run this on a hosted server on my PC, just to reproduce this.

Please wait

**Comment by ItzRonaldLG** [comment]
- I never use /reload, even if it is supported with all plugins i will use a server restart just to be sure.
- The server has 5GB ram, that has to be enough.. firstly it had 3 and i thought the same like you and upgraded 2 days ago to 5GB. But still crashes

**Comment by ItzRonaldLG** [comment]
- i even tried ''keepchunks'' becouse i was thinking maby it has trouble when the chunks are not loaded, That didnt change anything ;(

**Comment by GABRYCA** [comment]
Maybe a mine it's between 2 worlds...
Idk i'm not understanding the log, i'd delete all the mines and reset again manually, then when everything works, take a backup, just in case

**Comment by rbluer** [comment]
ItzRonaldLG I can probably help you with this, but unfortunately my organization blocks pastebin.com so I cannot see the stack trace.  I did review your mines and they look fine.
I'm work on adding a few new features and optimizations to this plugin and I'm focused on the prison-mines module right now.  I'd like to make sure this is no longer an issue, and if it is, I'd like to get it addressed within the next week or so.

**Comment by rbluer** [comment]
Release v3.2.0 includes a number of fixes and optimizations.  Please download the Prison plugin v3.2.0 when it is available.

ItzRonaldLG: I loaded your 26 mines with 4 others I have on my test server and it all worked just fine.  I TP'd to a few of your mines and they reset well with no problems.  What ever was causing the issues before, it looks like I got it resolved.  Tested in 1.14.4.
