### ISSUE TITLE
Set user ranks in game with command

### ISSUE THREAD

**Issue by Eddy0603** [PrisonTeam/Prison#139]
is there such command to set a user's rank in the game?

**Comment by GABRYCA** [comment]
No there isn't, there should be one to reset the rank of a player

**Comment by Eddy0603** [comment]
where? what's the command

**Comment by GABRYCA** [comment]
Sorry, i think i was wrong, as i don't remember and can't find a command to reset the player rank in game:(https://confluence.onultz.com/prison/docs/latest/en/ranks-guidebook)
 
Probably the only way it's delete from the prison folder (in the plugins), the playerdata about the player you want to delete the rank, i think...

Sorry for my mistake

**Comment by Eddy0603** [comment]
then how do i do prestiges?

like i want to reset a normal ladder rank and then have them rank up again etc

**Comment by GABRYCA** [comment]
https://github.com/PrisonTeam/Prison/issues/140

**Comment by Perksey** [comment]
There isn't a prestige system for Prison at the moment. Any references to one in the JSON config or the plugin's code are leftover from a scrapped prestige system we never finished.

**Comment by Perksey** [comment]
However, a rank set command is definitely long overdue and a worthy feature request for the next version i think.

**Comment by rbluer** [comment]
Closing this since rank commands have been added to the upcoming v3.2.1 release.

/ranks promote [player] [ladder]
/ranks demote [player] [ladder]
/ranks set rank [player] [rank] [ladder]

No immediate plans for adding a prestige system, but it's on the todo list.
