### ISSUE TITLE
what is the maxPrestige attribute on ladder_0.json file?

### ISSUE THREAD

**Issue by Eddy0603** [PrisonTeam/Prison#140]
I've set it to random numbers and still cannot use the command /rankup at the highest rank and cannot /prestige? Any fixes?

**Comment by GABRYCA** [comment]
Hi.
I'm sorry but prison have no prestige system, on our discord server there're 2 ways to have prestiges but without the /prestige command.

Thank you.

(to be faster, this is an english file of that on discord https://cdn.discordapp.com/attachments/543754309284659200/543754413819559936/Alternatively_prestige_system_english.it.en.docx )

**Comment by Perksey** [comment]
Ah that was added prior to a prestige system that we were working on, it just never got finished.
