### ISSUE TITLE
[19:37:03] [Server thread/INFO]: | Prison | Enable start... [19:37:03] [Server thread/INFO]: | Prison | Enabled Prison v3.2.0 in 74 milliseconds. [19:37:03] [Server thread/INFO]: | Prison | Mines enable start... [19:37:03] [Server thread/INFO]: | Prison | Loaded 1 mines [19:37:03] [Server thread/INFO]: | Prison | Mines enable succeeded, in 35 milliseconds. [19:37:03] [Server thread/INFO]: | Prison | Ranks enable start... [19:37:03] [Server thread/INFO]: | Prison | Ranks enable failed, in 1 milliseconds.

### ISSUE THREAD

**Issue by jatnam** [PrisonTeam/Prison#145]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: Core, Mines, Ranks, Shops, Cells, Gangs, Spigot, Sponge, etc.

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by jatnam** [comment]
I need help, i cant use ranks plugin

**Comment by jatnam** [comment]
it says No economy Plugin
But i had UltimateEconomy with VaultAPI
Ultimate economy and VaultApi load after that prison (mines and ranks), mines are working perfectly  but ranks are not

**Comment by jatnam** [comment]
1.15.1
the latest version of vault, prison and chestshop iconomy

**Comment by rbluer** [comment]
I just want to check, has this been resolved for you? 
If I remember correctly, we found a short term work around? But was wanting to follow up and confirm all is alright?

**Comment by rbluer** [comment]
Closing issue due to no response.  Can only assume your issues were resolved.  If not, please visit our discord site so we can help you better: https://discord.gg/396ed5F
