### ISSUE TITLE
Suggestion: Reset Mine Region to Saved State

### ISSUE THREAD

**Issue by TheMattVid** [PrisonTeam/Prison#149]
Suggestion:

Hi, I'm setting up a Prison server. I want to make a bunch of mines, but to mix things up, I don't want them to all just be cubes of blocks.

For some mines, I would like to have a region that I pre-build, and then when the mine resets, the mine returns exactly to that pre-built state.

For example, if I have a tree mine, I would build a small forest, and create the Prison Mine region around those trees. Then, players chop down the trees, and after awhile, the mine resets. After the reset, the trees are in the exact same position that they were in before. (This is sort of like how a minigame like skywars spawns you on a fresh map each game.) I figured that this would be a cool way for players to mine wood rather than a cube of logs.

I could create cool different varieties of mines if there was this "Regen" variety of mine in addition to the existing "Randomizer" one.

**Comment by rbluer** [comment]
Thanks for the suggestion.  Kind of a neat idea, but it maybe be out of scope of what prison currently is trying to accomplish?

You could actually do this with with minecraft schematic files, using world edit, with probably Async World Edit installed too... but basically create a schematic file of the original area, then just reload that template file.  Of course, the details on how to reload on a regular basis, and ensuring the players are TP'd out so they don't get trapped in a tree trunk.  Yeah I totally see why it could work with prison... right?

Another possibility is to use something like CoreProtect and roll back the changes on a regular basis.  But I think there could be risks if something goes wrong and you cannot roll back to the original state. I've had CoreProtect mess up once where things could be be undone (or maybe it was me?), but the bottom line if something goes wrong, then you're out of luck.

Another possibility is to just regen that chunk and let the minecraft engine build build everything.  Not 100% sure how reliable that would be with regenerating trunks and leaves.

Hmm... I don't think this fits in with what the prison plugin is currently doing.  But you do bring up some really good points too.  I'm needing to do some extensive work on integrations of WorldEdit and template files in another plugin, that perhaps  this may be a nice new feature or even a new module?  

I think it would be worth keeping this suggestion open and see what may become a reality in the near future?  Thanks so much for the suggestion. :)
  Blue

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
We may re-open it when we are at the stage of this suggestion as it might happen...
