### ISSUE TITLE
Guidebook down

### ISSUE THREAD

**Issue by Snaype** [PrisonTeam/Prison#150]
### Which module are you submitting this issue for?

Website/Guidebook
### Describe the issue you are experiencing.

503 Server Unavailable error.
### Describe the steps to reproduce the problem.

Open the guidebook link
### Anything else we need to know?
Please make a discord, it's way easier to ask for support with <3

**Comment by rbluer** [comment]
Sorry, that service was shutdown by the original creator of Prison and is currently obsolete. References to that link will be removed from the readme file with the future releases.
The content of that old site is available on the discord server in the #development channel as a PDF document.
Discord: https://discord.gg/396ed5F
