### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by AlexMeson** [PrisonTeam/Prison#164]
I have problems with the modules,
i installed the plugin and tried it right away, but none of the commands seemed to work,
i searched for solutions and tried the command /prisons modules and it shows no modules at all,i went to the editor of luckperms and abilited the permissions and i tried again and it did the same thing, just no modules at all so i checked the module config folder and it was empty.
![2020-04-30_19 28 19](https://user-images.githubusercontent.com/64606127/80740726-d3f8df00-8b18-11ea-9824-3ae80e15685b.png)

**Comment by GABRYCA** [comment]
Hi,
LuckPerms 5.x can make this type of error.
Please join ours discord server and head on to #support-bleeding, you'll find a prison build with the fix.

**Comment by rbluer** [comment]
The issue has to do with LuckPerms v5.0.x crashing older plugins that only support LuckPerms v4.4.1 or lower.  

Two solutions for you...

1. Downgrade to LuckPerms v4.4.1, which is on spigotmc.org's LuckPerm's page: 
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/history

2. Upgrade Prison to the pre-release version as found on the Discord server's #support-bleeding channel.  It works with all versions of LuckPerms and adds a ton of new features and fixes a few bugs.

https://discord.gg/396ed5F

If you have any other questions, you will get better support through the discord server. 

Thanks for trying Prison!  Hope you get it working shortly.

  Blue
