### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by G6Olivrrr** [PrisonTeam/Prison#165]
Prison is not working, it loads up but I get a constant message saying that there is a new version. I have downloaded the most recent version and tried several times stopping the server putting the plugin in and restarting and nothing would work. It loads up and when I do /pl it shows Prisons in it, but no commands for it work it always says unknown command. And I always just get an alert from it saying "version 3.2 is now available on the Spigot page" Is this just a bug?

**Comment by GABRYCA** [comment]
Hi, prison 3.2 have issues with Luckperms v5.x, you can fix it with one of these:
- Use a luckperms version like 4.x
Or
- Upgrade to the prison Alpha version 3.2.1 on the discord server, channel #support-bleeding

**Comment by G6Olivrrr** [comment]
Wow, thanks for such a quick response, really appreciate that. It works now thank you for that.

**Comment by GABRYCA** [comment]
Fine, thank you.
