### ISSUE TITLE
Website Not working

### ISSUE THREAD

**Issue by BlockSpeed03** [PrisonTeam/Prison#167]
I can not log in to the website (wiki)

**Comment by rbluer** [comment]
The original owner took it offline.  There is nothing I can do about the dead links until I push out the next release, which should be soon.

Our current discord server:
https://discord.gg/396ed5F

Our current documents:
https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_000_toc.md

I recommend you use the pre-release version of Prison which can be found on the discord server under the #support-bleeding channel.  

There has been a ton of bug fixes, performance enhancements, and a bunch of new features.

If you need help, please visit the discord server and we can help you out better there.

  Enjoy!
   Blue
