### ISSUE TITLE
i dont know how to setup prison ranks and the website on the official plugin page leads to an unknown website

### ISSUE THREAD

**Issue by GamingProduction** [PrisonTeam/Prison#168]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Example: Core, Mines, **

**### Ranks**

**, Shops, Cells, Gangs, Spigot, Sponge, etc.

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by rbluer** [comment]
https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_000_toc.md

The current documentation is available at the above URL.
