### ISSUE TITLE
No modules

### ISSUE THREAD

**Issue by Aksm1234** [PrisonTeam/Prison#169]
When i installed the plugin there were no modules not even mines or ranks nothing.

**Comment by GABRYCA** [comment]
If you're using Prison 3.2 and you've installed Luckperms 5.x this's a known issue

You can do 2 things:

1) Join the discord server and head on the #support-bleeding channel, there you'll find the alpha where the issue's fixed

OR

2) Downgrade to luckperms 4.x

Thank you, you can find the discord server link on the plugin page with a purple button

**Comment by Aksm1234** [comment]
i will
