### ISSUE TITLE
Question..

### ISSUE THREAD

**Issue by Kajus11** [PrisonTeam/Prison#172]
Hello, i would like to know how to get modules?

**Comment by Crystalz-PrisonSupport** [comment]
Hi! I am xCrystalz_, Manager of the Prison Plugin and one of the support team members. Please can you explain this is more details?

**Comment by GABRYCA** [comment]
You should already have Ranks and Mines when you install the plugin.
If it's not working, you might have an issue with LuckPerms 5.x.
You can do 2 things:
Downgrade to LuckPerms 4.x
Or
Join the discord server and try one of the Alpha version, we've fixed that.

**Comment by rbluer** [comment]
The discord link is here: https://discord.gg/aemnrF

As Gabryca mentioned, there are two solutions to your problem: Downgrade LuckPerms to v4.4.1 or upgrade Prison to the pre-release version of Prison, which is found on the discord server under #alpha-versions.

Prison v3.2.0 only supports LuckPerms v4.4.1 or lower.  The pre-release version of Prison supports all versions of LuckPerms.

The pre-release version of Prison has a lot of new features, bug fixes, and performance improvements.  It's recommended that you use this version, along with the latest release of LuckPerms v5.0.x.

(I'm keeping this issue open for now so others can find the solution easier).

**Comment by Kajus11** [comment]
Oh okei

**Comment by rbluer** [comment]
I should also mention that documentation can be found here:

https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_000_toc.md

**Comment by Kajus11** [comment]
Thank you for help!! now its working fine! Thank u alot<3!

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
