### ISSUE TITLE
Просьба фаната

### ISSUE THREAD

**Issue by Warmen-zm** [PrisonTeam/Prison#183]
Hi. Very cool plugin. I used the old version, but I can't install the new one. you need a file extension (.jar). It would be cool if you release one. It would be even cool if the Russian version appears. I watched the video on YouTube and I'm waiting for the next version :)

**Comment by Norbik1004** [comment]
Hi! You can download newest releases on [Spigot](https://www.spigotmc.org/resources/prison.1223/). If you want you can join our [Discord Server](https://discord.com/invite/DCJ3j6r) to get access to alpha versions and faster support!

**Comment by GABRYCA** [comment]
I guess this's fixed so, thank you for your support!
