### ISSUE TITLE
https://pastebin.com/eXeBrkd3

### ISSUE THREAD

**Issue by ducdzz61** [PrisonTeam/Prison#184]
i don't know
pls check link: https://pastebin.com/eXeBrkd3
thanks sir

**Comment by ducdzz61** [comment]
https://pastebin.com/rbZTzBTb

**Comment by GABRYCA** [comment]
It's an error related to the GUI, please join the discord server and try an alpha

**Comment by ducdzz61** [comment]
thanks sir!

**Comment by GABRYCA** [comment]
I'm going to close this issue as it should've been fixed within alpha and we'll probably release a new release soon.
