### ISSUE TITLE
This is the translation Chinese

### ISSUE THREAD

**Issue by M1032** [PrisonTeam/Prison#240]
[module_conf.zip](https://github.com/PrisonTeam/Prison/files/9690215/module_conf.zip)

**Comment by rbluer** [comment]
I am so sorry for not seeing this earlier.

I'll review these changes and add then to the current alpha release.

I greatly thank your help and this submission.

In the future, please use our discord server and ping me to get my attention:  @RoyalBlueRanger

thank so much for your contributions!!
  - Blue

**Comment by rbluer** [comment]
Greetings M1032,

Good news!  I added your Chinese translation files to prison!

Thanks so much for helping us!

These files are now a part of prison, and they will be included in all future releases, starting with the next alpha release.

Thanks again for your help!  If you need anything, please contact on our discord server and we'll be happy to help.

  - Blue
