### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by alfredcort** [PrisonTeam/Prison#249]
https://mclo.gs/w0EFaBV

Using ver: 3.3.0-alpha.14b

**Comment by TheMadog24** [comment]
nbtapi can't be updated until the next release. Please use the Discord for any issues, not the Github.

**Comment by rbluer** [comment]
FYI... I just updated the nbt library to v2.11.2 and will try to produce a new build later tonight.  I will be posting it to our discord server's alpha channel.

But I don't think there will be any issues with using the alpha.14b release since prison is using the very basics from that nbt library.

**Comment by alfredcort** [comment]
> nbtapi can't be updated until the next release. Please use the Discord for any issues, not the Github.

My bad, I know now for the future. :)
