### ISSUE TITLE
Enhanced multiworld support

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#48]
A request that keeps reappearing is better multi-world support for Prison. It's definitely useful for server owners that have different worlds for different things, and Prison should facilitate this process.

The problems that currently exist without multi-world support are as follows.
* Broadcasts show to all worlds.
* Chat format shows in all worlds.
* Events are responded to from all worlds.

The goals of enhanced multi-world support are as follows.
- [ ] Broadcasts show only to people in certain worlds. (API)
- [ ] WorldManager to store which worlds are Prison worlds. (API)
- [ ] Configuration `config.yml` updated to restrict worlds. (Implementation)
- [ ] Chat format only affects Prison worlds. (Ranks)
- [ ] Mines and Ranks updated to use API broadcast method. (Mines/Ranks)

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
