### ISSUE TITLE
New event system

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#49]
Currently, the event system in Prison is rushed and very sparse. There are very little events, and listeners have no control over which exact events they listen to... even for event priorities.

The new event system will be modeled after [lucko's helper event system](https://github.com/lucko/helper). 

- [ ] New system modeled after helper's event system.
- [ ] Expand events to include all player and block events in Spigot.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
