### ISSUE TITLE
WorldEdit support for selection system

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#51]
WorldEdit has a very advanced selection system that fits right in with all of its world manipulation features. Currently, in Prison, only the `tech.mcprison.prison.selection` system may be used to create such selections. WorldEdit support would be used in place of the Prison selection system if the server has it.

- [ ] Selection as an integration (API)
- [ ] Include WorldEdit integration (Implementation)
- [ ] Include Prison integration (Implementation)

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
