### ISSUE TITLE
New configuration system

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#53]
Currently, in Prison, to create a configuration file, one must serialize a class containing all of the variables. If new options are added, the user has to delete his configuration file, which is very stupid.

Goals of the new system:
- [ ] Poll for configuration changes to eliminate the need for reloads! ([see here](https://docs.oracle.com/javase/tutorial/essential/io/notification.html)).
- [ ] New configuration options simply have themselves added with their defaults to the configuration file.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
