### ISSUE TITLE
World protection integration

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#54]
Integration with world protection plugins, such as WorldGuard, would allow mines systems to integrate with ranks systems to ensure only certain ranks would be able to access it.

**Comment by DylanFPS** [comment]
If servers really need this, they can do this themselves. Ranks can give players permissions, and it'll be easier (for us) to just setup WorldGuard manually for permissions.

**Comment by faizaand** [comment]
We did try this with Prison 2 a while ago and it ended up breaking protections entirely. We'll see though.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
