### ISSUE TITLE
Autoblock and autosmelt

### ISSUE THREAD

**Issue by MCTyler** [PrisonTeam/Prison#58]
Would it be Possible to include features like these, [Autopickup](https://dev.bukkit.org/projects/autopickup), Directly into the plugin? Especially the **Auto Pickup** and **Auto Block** are particularly useful for a Prison Plugin. I'm afraid that that plugin will no longer be maintained and those features will be lost. 

Thanks Very Much for consideration! Keep up the good work!

**Comment by DylanFPS** [comment]
Hmmm maybe this could be part of the Mines module. In Prison 2 we used to have autoblock and autosmelt, so I don't see why we shouldn't add it again.

**Comment by MCTyler** [comment]
AutoPickup is critical when you have Multiple players mining in the same mine. Be careful though, some of the "badly coded" autopickup plugins cancel the exp orbs from mining but the one I referenced does not!

**Comment by DylanFPS** [comment]
Good to know. This will most likely be in Prison 3.1 if the other developers approve.

**Comment by DylanFPS** [comment]
Also, I believe that the Mines module has autopickup anyway, there is just no toggle.

**Comment by MCTyler** [comment]
[https://imgur.com/ozVsQoE](url)

**Comment by DylanFPS** [comment]
PR #47 marks the start of these tools, autopickup is currently the only powertool that works atm - autosmelt requires an entity system to be made and autoblock requires a fair amount of bugs to be fixed.

**Comment by GABRYCA** [comment]
We're adding this feature and it's already in experimental with the Alpha version.
There is also AutoPickup

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.

**Comment by GABRYCA** [comment]
Already added some time ago.... months as an experimental feature, there're some compatibility issues sometimes between version-blocks and enchants, but should be pretty much ready
