### ISSUE TITLE
Cells Module

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#6]
The Cells module's purpose is to add functional cells to the game. In the Prison game-type, Cells are rented areas of land that players can use to store their items. They act as a functional living space. They are one of the two common types of player areas that Prison servers use (the other is plots, which Prison will not be providing). 

The Cells module will make it simple to create these cells. The checklist below is subject to change as feature ideas are added.
- [ ] Basic cell loading and saving
- [ ] Basic cell land protection functionality (i.e. protected doors, land)
- [ ] Permissions
- [ ] Multiple users

**Comment by SirFaizdat** [comment]
Moved to a future release, due to time constraints.

**Comment by DMP9-MC** [comment]
Development started, probably will get it done by initial release.

**Comment by DMP9-MC** [comment]
**UPDATE** Because of time constraints, cells has been moved to future release.

**Comment by faizaand** [comment]
@DylanFPS You wanted to take this?

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
