### ISSUE TITLE
Feature request - Prestige

### ISSUE THREAD

**Issue by svnxd** [PrisonTeam/Prison#68]
Prestige ranks - Once you get to Z you can prestige, this will make you go back down to A and give you Prestige1 as an example. I honestly don't know what else to say.

**Comment by SevenSlayy** [comment]
@DylanFPS any updates on this?

**Comment by DylanFPS** [comment]
Sorry the teams been inactive for a while, so we haven't been able to work on 3.1.

**Comment by SevenSlayy** [comment]
eta?

**Comment by DylanFPS** [comment]
Can't provide, sorry.

**Comment by DylanFPS** [comment]
Started working on it today, should hopefully be ready soon

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.

**Comment by GABRYCA** [comment]
Already "done" about one or two months ago, just needs heavy testing but looks like there aren't issues reported for now
