### ISSUE TITLE
Shops Module

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#9]
The Shop module's primary goal is to add shops to the game. Prison servers use shops to allow players to sell the items they mine.

Shops are currently scheduled to be the last module. As a result, they are not planned yet. This issue will be updated when the shops are planned.

- [ ] /sell [all|hand] command
- [ ] sell all/hand signs
- [ ] shops attached to ranks
- [ ] sell boosts, autosell when full, etc.

**Comment by SirFaizdat** [comment]
Moved to a future release, due to time constraints.

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
