### ISSUE TITLE
The Electric Update

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#92]
The next major release of Prison, the Electric Update (API 4), will contain massive overhauls to the code structure. 

**Main goals**
- [ ] Remove Prison's multi-platform support, which caused a lot of unnecessary overhead and code jumbling without multiple platforms to, well, support.
- [ ] Remove Prison's third-party module system, since third-party features can be added via another Spigot plugin anyway (no need for our own API).
- [ ] Revamp the storage and localization systems (since these data are now static and not dynamically defined).
- [ ] Use lucko's fantastic [helper](https://github.com/lucko/helper) system to reduce the footprint of our codebase and make things easier.

This is a primarily structural release, but user-facing features are planned as well!
- [ ] Implement scoreboard support.
- [ ] Implement GUI menus.
- [ ] Make mine and rank data fully editable in-game.
- [ ] Expand integrations for permissions and economy systems.

Current target release date is sometime in **August 2018**.

**Comment by DylanFPS** [comment]
~~Bruh don’t assign that to me I’m going on tour in August 😂😂~~

Sounds good

**Comment by faizaand** [comment]
@DylanFPS I'm going to sit down and take a look at the current architecture of the plugin and see how it can be optimized further. The goal is to get rid of as many bloated features as possible. If the module system is actually optimal, then it'll stay!

**Comment by DylanFPS** [comment]
Alright. In my opinion, we should keep the module system, but if the enable/disable system is still in there remove it as that's bloated.
