### ISSUE TITLE
My Mines are broken.

### ISSUE THREAD

**Issue by MLean** [PrisonTeam/Prison#96]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
I make my mines and they don't go into the config but they register in game. So when I restart my server all the mines are gone. I made A - Z mines and only A - E register.

### Describe the steps to reproduce the problem.
Make mines A - Z and restart the server, only A - E show up for me

### Anything else we need to know?
Said it all

**Comment by MLean** [comment]
bump

**Comment by DylanFPS** [comment]
Closed for inactivity
